#!/usr/bin/env node
var colors = require('colors');
var Table = require('cli-table');
var fs = require('fs');

var home = process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE;

if (fs.existsSync(home+'/.ethreal')) {
  var config = JSON.parse(fs.readFileSync(home+'/.ethreal', 'utf8'));
}else{
  var config = {
    "crypto": [
      {
          "symbol": "BTC"
        , "color": "magenta"
      },
      {
          "symbol": "BCH"
        , "color": "green"
      },
      {
          "symbol": "ETH"
        , "color": "cyan"
      },
      {
          "symbol": "LTC"
        , "color": "yellow"
      }
    ]
  };
}

const httpromise = function(url) {
  // return new pending promise
  return new Promise((resolve, reject) => {
    // select http or https module, depending on reqested url
    const lib = url.startsWith('https') ? require('https') : require('http');
    const request = lib.get(url, (response) => {
      // handle http errors
      if (response.statusCode < 200 || response.statusCode > 299) {
         reject(new Error('Failed to load page, status code: ' + response.statusCode));
       }
      // temporary data holder
      const body = [];
      // on every content chunk, push it to the data array
      response.on('data', (chunk) => body.push(chunk));
      // we are done, resolve promise with those joined chunks
      response.on('end', () => resolve(body.join('')));
    });
    // handle connection errors of the request
    request.on('error', (err) => reject(err))
    })
};

const loadTable = function(parsed){

  var change24h = (parsed.percent_change_24h >= 0)
        ? colors.green(' '+parsed.percent_change_24h)
        : colors.red(parsed.percent_change_24h);

  var change7d = (parsed.percent_change_7d >= 0)
        ? colors.green(' '+parsed.percent_change_7d)
        : colors.red(parsed.percent_change_7d);


  var color = config.crypto.filter(function(c){
    return c.symbol == parsed.symbol;
  });

  var c = color[0].color;

  table.push(
      [colors[c](parsed.name), colors[c]("$"+parsed.price_usd), change24h, change7d]
  );

  return table;
}

const configSymbols = function() {
  return config.crypto.map(function(c){
    return c.symbol;
  });
}

var table = new Table({
  head: ['Crypto', 'USD', '24h', '7d'],
  chars: { 'top': '═' , 'top-mid': '╤' , 'top-left': '╔' , 'top-right': '╗'
         , 'bottom': '═' , 'bottom-mid': '╧' , 'bottom-left': '╚' , 'bottom-right': '╝'
         , 'left': '║' , 'left-mid': '╟' , 'mid': '─' , 'mid-mid': '┼'
         , 'right': '║' , 'right-mid': '╢' , 'middle': '│' }
});

httpromise('https://api.coinmarketcap.com/v1/ticker/')
  .then(function(data){
    data = JSON.parse(data);
    symbols = configSymbols();

    var sort = data.filter(function(c) {
      return symbols.indexOf(c.symbol) >= 0;
    });

    return sort;
  })
  .then(function(data){
    var table = null;
    data.forEach(function(c){
      table = loadTable(c);
    });
    return table;
  })
  .then(function(t){
    console.log(t.toString());
  });
